(function registerRecipeMasterRules(root) {
  "use strict";

  const rules = {
    cardSelectors: [
      ".wprm-recipe-container",
      "[id^='wprm-recipe-container-']",
      ".tasty-recipes",
      ".tasty-recipes-entry-content",
      ".mv-create-card",
      ".mv-create-card-style",
      ".wp-block-mv-recipe-card",
      ".easyrecipe",
      ".easy-recipe",
      ".ERSDetails",
      ".zip-recipes",
      ".zrdn-recipe-container",
      ".cookbook-recipe",
      ".recipe-card",
      ".recipe-card-container",
      ".recipe-content",
      ".recipe-summary",
      ".recipe-block",
      ".recipe-module",
      ".hrecipe",
      "[itemtype='https://schema.org/Recipe']",
      "[itemtype='http://schema.org/Recipe']",
      "[itemtype*='schema.org/Recipe']",
      "[data-recipe-id]",
      "[data-recipe-card]"
    ],

    ingredientSelectors: [
      "[itemprop='recipeIngredient']",
      "[itemprop='ingredients']",
      ".wprm-recipe-ingredient",
      ".tasty-recipes-ingredients li",
      ".mv-create-ingredients li",
      ".ERSIngredients li",
      ".zip-recipes-ingredients li",
      ".recipe-ingredients li",
      ".ingredients li",
      "[class*='ingredient-list'] li",
      "[data-ingredient]"
    ],

    instructionSelectors: [
      "[itemprop='recipeInstructions']",
      ".wprm-recipe-instruction",
      ".tasty-recipes-instructions li",
      ".tasty-recipes-instructions p",
      ".mv-create-instructions li",
      ".ERSInstructions li",
      ".zip-recipes-instructions li",
      ".recipe-instructions li",
      ".recipe-directions li",
      ".instructions li",
      ".directions li",
      "[class*='instruction-list'] li",
      "[class*='direction-list'] li",
      "[data-instruction]"
    ],

    adSelectors: [
      "ins.adsbygoogle",
      ".google-auto-placed",
      "[id^='google_ads_iframe_']",
      "[id^='div-gpt-ad-']",
      "[data-ad-slot]",
      "[data-ad-unit]",
      "[data-ad-container]",
      ".adthrive-ad",
      "[class*='adthrive-ad']",
      "[id*='adthrive-ad']",
      ".mediavine-ad",
      ".mv-ad-box",
      "[data-mediavine-ad]",
      ".raptive-ad",
      "[class*='raptive-ad']",
      ".cafemedia-ad",
      ".shemedia-ad",
      ".ezoic-ad",
      "[id^='ezoic-pub-ad-']",
      ".dfp-ad",
      ".dfp-ad-container",
      ".advertisement",
      ".advertisement-wrapper",
      ".ad-container",
      ".ads-container",
      ".ad-wrapper",
      ".sponsored-ad",
      ".sticky-ad",
      ".adhesion-ad",
      ".footer-ad",
      ".header-ad",
      ".sidebar-ad",
      "[aria-label='advertisement' i]",
      "[aria-label='ads' i]"
    ],

    floatingMediaSelectors: [
      ".sticky-video",
      ".floating-video",
      ".video-sticky",
      "[class*='sticky-video']",
      "[class*='floating-video']",
      "[data-sticky-player]",
      ".jwplayer.jw-flag-floating",
      ".jwplayer.jw-flag-small-player",
      ".video-player-sticky",
      ".mv-video-target-sticky",
      ".mediavine-video__sticky-container"
    ],

    overlayCandidateSelectors: [
      "dialog[open]",
      "[role='dialog']",
      "[aria-modal='true']",
      ".pum-overlay",
      ".pum-container",
      ".om-holder",
      "[class*='newsletter-modal']",
      "[id*='newsletter-modal']",
      "[class*='email-popup']",
      "[id*='email-popup']",
      "[class*='subscribe-modal']",
      "[id*='subscribe-modal']",
      "[class*='signup-modal']",
      "[id*='signup-modal']",
      "[class*='promo-modal']",
      "[id*='promo-modal']",
      "[class*='interstitial']",
      "[class*='exit-intent']",
      "[class*='popup-overlay']"
    ],

    nuisanceText: /newsletter|mailing list|join (?:our|the) list|sign up (?:for|to get|and receive)|get (?:our|free|the latest|more) .*?(?:recipes|updates|offers)|(?:recipes|updates|offers) (?:sent|delivered) .*?inbox|enter your email|email (?:me|us) .*?(?:recipes|updates)|before you go|don['’]t miss|special offer|download (?:our|the) app|install (?:our|the) app|enable notifications|allow notifications|turn on notifications|follow us|save \d+%|claim (?:your|this) (?:offer|discount)/i,
    protectedText: /age verification|verify (?:your )?age|are you (?:21|18)|(?:must|need to) be (?:21|18)|date of birth|subscriber[ -]only|subscription required|already a subscriber|sign in to (?:continue|access|read)|log in to (?:continue|access|read)|purchase (?:a )?subscription|cookie settings|cookie consent|manage consent|consent preferences|privacy choices|do not sell|gdpr|ccpa/i,

    headingIngredients: /^(?:ingredients?|what you(?:'|’)ll need|you(?:'|’)ll need)$/i,
    headingInstructions: /^(?:instructions?|directions?|method|preparation|steps?|how to make(?: it)?|how to prepare)$/i,

    siteCardSelectors: {
      "allrecipes.com": ["#recipe_1-0", "[class*='recipe-container']", "[data-id='main-recipes']"],
      "foodnetwork.com": [".o-Recipe", "[class*='recipe-body']"],
      "delish.com": ["[class*='recipe-body']", "[data-node-id='recipe']"],
      "eatingwell.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "thekitchn.com": ["[id*='recipe']", "[class*='Recipe']"],
      "simplyrecipes.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "tasteofhome.com": [".recipe", "[class*='recipe-content']"],
      "recipetineats.com": [".wprm-recipe-container"],
      "food.com": [".recipe", "[class*='recipe-body']"],
      "bonappetit.com": ["[data-testid='IngredientList']", "[data-testid='InstructionsWrapper']"],
      "seriouseats.com": ["#structured-project__steps_1-0", "[class*='recipe-body']"],
      "foodandwine.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "epicurious.com": ["[data-testid='IngredientList']", "[data-testid='InstructionsWrapper']"],
      "cooking.nytimes.com": ["[class*='recipe']"],
      "thespruceeats.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "marthastewart.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "kingarthurbaking.com": [".recipe", "[class*='recipe__']"],
      "bbcgoodfood.com": [".recipe", "[class*='recipe']"],
      "liquor.com": ["#recipe_1-0", "[class*='recipe-content']"],
      "diffordsguide.com": ["[class*='recipe']"],
      "punchdrink.com": ["[class*='recipe']"],
      "vinepair.com": ["[class*='recipe-card']", "[class*='recipe']"],
      "makemeacocktail.com": ["[class*='recipe']", "[class*='cocktail']"],
      "tipsybartender.com": ["[class*='recipe']", "[class*='ingredients']"],
      "absolutdrinks.com": ["[class*='recipe']", "[class*='ingredients']"]
    },

    priorityDomains: [
      "allrecipes.com", "foodnetwork.com", "delish.com", "eatingwell.com", "thekitchn.com",
      "simplyrecipes.com", "tasteofhome.com", "recipetineats.com", "loveandlemons.com",
      "sallysbakingaddiction.com", "spendwithpennies.com", "natashaskitchen.com", "food.com",
      "bonappetit.com", "seriouseats.com", "foodandwine.com", "epicurious.com", "cooking.nytimes.com",
      "thespruceeats.com", "tastingtable.com", "parade.com", "southernliving.com", "bhg.com",
      "marthastewart.com", "thepioneerwoman.com", "bettycrocker.com", "pillsbury.com",
      "kingarthurbaking.com", "americastestkitchen.com", "bbcgoodfood.com", "sugarspunrun.com",
      "100daysofrealfood.com", "inspiredtaste.net", "budgetbytes.com", "gimmesomeoven.com",
      "halfbakedharvest.com", "joyfoodsunshine.com", "preppykitchen.com", "cookieandkate.com",
      "livelytable.com", "thecozycook.com", "indianhealthyrecipes.com", "downshiftology.com",
      "themodernproper.com", "lecremedelacrumb.com", "pinchofyum.com", "skinnytaste.com",
      "heygrillhey.com", "thesaltymarshmallow.com", "momontimeout.com", "chilipeppermadness.com",
      "bromabakery.com", "healthyrecipesblogs.com", "feelgoodfoodie.net", "southernbite.com",
      "therecipecritic.com", "dearcrissy.com", "mediterraneantaste.com", "billyparisi.com",
      "iheartnaptime.net", "hot-thai-kitchen.com", "hungryhuy.com", "acouplecooks.com",
      "alexandracooks.com", "laurafuentes.com", "minimalistbaker.com", "theforkedspoon.com",
      "sipandfeast.com", "iowagirleats.com", "whatsgabycooking.com", "liveeatlearn.com",
      "cafedelites.com", "barefeetinthekitchen.com", "moonandspoonandyum.com",
      "myheavenlyrecipes.com", "cheflolaskitchen.com", "africanbites.com", "howsweeteats.com",
      "muydelish.com", "kitchensanctuary.com", "veggiedesserts.com", "aspicyperspective.com",
      "savorynothings.com", "acozkitchen.com", "fifteenspatulas.com", "handletheheat.com",
      "mykoreankitchen.com", "cookpad.com", "butterbeready.com", "chelseasmessyapron.com",
      "fromvalerieskitchen.com", "honest-food.net", "amandascookin.com", "addapinch.com",
      "modernhoney.com", "littlesunnykitchen.com", "simpleveganblog.com", "thefoodcharlatan.com",
      "ohsweetbasil.com", "averiecooks.com", "liquor.com", "diffordsguide.com", "punchdrink.com",
      "vinepair.com", "imbibemagazine.com", "makemeacocktail.com", "tipsybartender.com", "bevvy.co",
      "absolutdrinks.com", "thebar.com", "abarabove.com", "advancedmixology.com",
      "jeffreymorgenthaler.com", "alcademics.com", "cocktailwonk.com", "gastronomblog.com",
      "moodymixologist.com", "cocktailsandshots.com", "cocktailchemistrylab.com",
      "thecocktailsociety.uk", "craftandcocktails.co", "drinkingwithchickens.com",
      "stirandstrain.com", "beautifulbooze.com", "summitsips.com", "anothercocktailblog.com",
      "thecocktailblog.com", "chilledmagazine.com", "alcoholprofessor.com", "craftybartending.com",
      "mindfulmocktail.com", "mocktail.net", "abeautifulmess.com", "thelittleepicurean.com",
      "coffeegeek.com", "bacardi.com"
    ]
  };

  root.RecipeMasterRules = Object.freeze(rules);
})(typeof globalThis !== "undefined" ? globalThis : window);
